<array>
            <dict>
                <!-- Okemo -->
                <key>javascript-url</key>
                <string>https://trailers.apple.com/appletv/us/js/application.js</string>
                <key>javascript-url-signature</key>
                <data>kXmT89FEvwQ0DyVGkyJe/UuVdamvqyWb++Vk+yaJqGUCqibB7MUom2BvJXrdGhiFVZr7Rp+XaHxxJ1l+lk5MNKSAuWRaDvQ6H6STUcP+kAYOQ1ueBX7ih5hoDWJcMWfIMQ6a46e93GBg1ehczrFhFiwFuQ8/YVVo24a0vmVbKz/NH0tqKxq2+3fIZzUbOhUdYq+fa4rIPuIvNASTrhOxByG8xQW/mPQREKaeoASS35OfNIMGopkesqIz9lQbpsg+Ow6GfXjvsXonIuXeSQcpkBtxZUFNILcW6vFyEFcyzyDbFWi/aQkyOkw4gYmS7+CzDObV+vHImBe3DQPt4ES7lQ==</data>
                <key>auth-type</key>
                <string>js</string>
                <key>enabled</key>
                <string>YES</string>
                <key>menu-title</key>
                <string>Trailers</string>
                <key>merchant</key>
                <string>movie-trailers-v2</string>
                <key>minimum-required-version</key>
                <string>7.0</string>
                <key>preferred-order</key>
                <string>6000</string>
                <key>feed-resources</key>
                <dict>
                    <key>SHOWTIMES_AVAIALABLE</key>
                    <true /> </dict>
                <key>menu-icon-url</key>
                <dict>
                    <key>720</key>
                    <string>http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/images/atv7/movie-trailers@720.png</string>
                    <key>1080</key>
                    <string>http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/images/atv7/movie-trailers@1080.png</string>
                </dict>
                <key>menu-icon-url-version</key>
                <string>20.0</string>
                <key>screensaver</key>
                <array>
                    <dict>
                        <key>preview-image</key>
                        <dict>
                            <key>720</key>
                            <dict>
                                <key>image</key>
                                <string>http://trailers.apple.com/appletv/us/images/icons/trailerslogo.png</string>
                            </dict>
                            <key>1080</key>
                            <dict>
                                <key>image</key>
                                <string>http://trailers.apple.com/appletv/us/images/icons/trailerslogo.png</string>
                            </dict>
                        </dict>
                        <key>canonical-name</key>
                        <string>ATVFeedScreensaverPhotos</string>
                        <key>has-multiple-photo-collections</key>
                        <false />
                        <key>photo-collection-identifier</key>
                        <string>trailers-posters</string>
                        <key>preferred-order</key>
                        <integer>475</integer>
                    </dict>
                </array>
            </dict>
        </array>
